# Log all requests at the Metadata level.
apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "RequestReceived"
  - "ResponseStarted"
rules:
  - level: Request
    verbs: ["create", "delete", "update", "patch"]
    # namespaces: ["default"]
    omitManagedFields: true
    resources:
      - group: ""
        resources: ["container"]
      - group: "" # core
        resources: ["pods", "pods/*"]
      - group: "" # core
        resources: ["services", "services/*"]
      - group: "apps" # core
        resources: ["deployments", "deployments/*"]
      - group: "apps" # core
        resources: ["replicasets", "replicasets/*"]
      - group: "apps" # core
        resources: ["statefulsets", "statefulsets/*"]
      - group: "discovery.k8s.io"
        resources: ["endpointslices"]
      # - group: ""  # core
      #   resources: ["replicacontrollers", "replicationcontrollers/scale", "replicationcontrollers/status"]
  - level: Request
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: "" # core
        resources: ["persistentvolumeclaims", "persistentvolumeclaims/status"]
      - group: "" # core
        resources: ["persistentvolumes", "persistentvolumes/status"]
  - level: None
    verbs: ["get", "watch"]
    resources:
      - group: "" # core
        resources: ["nodes", "endpoints", "configmaps"]
      - group: "" # core
        resources: ["events"]
      - group: "events.k8s.io"
        resources: ["events"]
      - group: "coordination.k8s.io"
        resources: ["leases"]
