# Log all requests at the Metadata level.
apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "ResponseStarted"
rules:
  - level: Request
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["pods", "pods/status", "replicacontrollers", "container"]
      - group: "apps"
        resources: ["deployments", "replicasets", "statefulsets"]
  - level: Request
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["persistentvolumeclaims", "persistentvolumes"]
  - level: None
    verbs: ["get", "watch"]
    resources:
    - group: "" # core API group
      resources: ["endpoints", "nodes", "services", "configmaps"]
    - group: "coordination.k8s.io"
      resources: ["leases"]